# Generated by Django 3.0.6 on 2020-05-25 09:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='资讯内容'),
        ),
    ]
