# Generated by Django 3.0.6 on 2020-05-29 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200525_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 5, 48, 53, 338012, tzinfo=utc), verbose_name='保存日期'),
        ),
    ]
