# Generated by Django 3.0.6 on 2020-06-16 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200529_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='news_1.jpeg', upload_to='img/news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 3, 25, 33, 877833, tzinfo=utc), verbose_name='保存日期'),
        ),
    ]
